#!/usr/bin/env python
# coding: utf-8

# ##  CycleGAN for Synthetic Image Generation
# 
#  <sub> <a href="https://jmhuer.github.io/mini_book/_build/html/docs/portfolio.html" style="color: red; text-decoration: underline;text-decoration-style: dotted;">← Back to Projects</a> </sub>
# 
# <img src="../../../../images/smoke.png" align="center"/>
# 
# <br>
# 
# Collecting data can be expensive and in certain use cases dangerous to acquire. One such example is smoke data. There are many applications relevant to smoke detection with a camera. To skip the data collection stage we create a synthetic dataset of smoky images..
# <br>
# 
# 
# 
# ## Synthetic data
# ---
# 
# Synthetic data is information that's artificially manufactured rather than generated by real-world events. Synthetic data is created algorithmically, and it is used as a stand-in for test datasets of production or operational data, to validate mathematical models and, increasingly, to train machine learning models.
# 
# The Full repository for generation and classification is available here: https://github.com/patel996/smoke-detection
# 
# 
# ## CycleGANs
# ---
# 
# The Cycle Generative Adversarial Network, or CycleGAN, is an approach to training a deep convolutional neural network for image-to-image translation tasks. The Network learns mapping between input and output images using unpaired dataset.
# 
# <img src="../../../../images/cyclegan2.png" align="center"/>
# 
# The common example given is one in which we convert horses to zebras and vice versa
# 
# <img src="../../../../images/CycleGAN.jpeg" align="center"/>
# 
# <br>
# <br>
# 
# ## Generation results
# ---
# 
# Below we have some randomly selected examples using a validation set:
# 
# <img src="../../../../images/smoke2.png" align="center"/>
# 
# <br>
# <br>
# 
# 
# ## Testing Classification Results
# ---
# 
# Pretrained Resnet-50 model is used to classify the smoky images from the non-smoky ones. It can be found in the Fire-Smoke-Detection folder, adapted from https://github.com/imsaksham-c/Fire-Smoke-Detection.
