#######################################################################################
# Book settings
title : Juan
author: Juan Huerta
logo: '0.png'
collapse_inactive_sections: true
collapse_inactive_chapters: true

# Information about where the book exists on the web
description: >-
  A personal website with data science resources and project tutiorials

#######################################################################################
# Execution settings
execute:
  execute_notebooks           : cache

#######################################################################################
# HTML-specific settings
html:
  home_page_in_navbar         : false

# #######################################################################################
# Interact link settings
notebook_interface            : "notebook"

#######################################################################################
# Launch button settings
repository:
  url                         : https://github.com/jmhuer/jmhuer.github.io/tree/master/mini_book/docs/independent #if this stops wokring i saved repo personal_projects
  path_to_book                : "mini_book"

binder:
  binderhub_url               : "https://mybinder.org"
  text                        : "Launch binder"

latex:
  latex_engine                : "xelatex"
  latex_documents:
    targetname: book.tex
